branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
git:
  depth: false
matrix:
  include:
    - os: linux
      dist: bionic
      language: csharp
      mono: none
      dotnet: 2.2.401
      script: "./build.sh"
    - os: osx
      language: csharp
      mono: none
      dotnet: 2.2.401
      script: "./build.sh"
