trigger:
  branches:
    include:
    - master
    - release-*
jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreInstaller@2
    inputs:
      packageType: 'sdk'
      version: '3.1.302'
  - script: ./build.cmd
    displayName: 'Build the project'
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DotNetCoreInstaller@2
    inputs:
      packageType: 'sdk'
      version: '3.1.302'
  - script: ./build.sh
    displayName: 'Build the project'
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: DotNetCoreInstaller@2
    inputs:
      packageType: 'sdk'
      version: '3.1.302'
  - script: ./build.sh
    displayName: 'Build the project'
