trigger:
  branches:
    include:
    - master
    - release-*
jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '3.1.100'
  - script: ./build.cmd
    displayName: 'Build the project'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '3.1.100'
  - script: ./build.sh
    displayName: 'Build the project'
